Factory/Models/Machine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<MechanicMachine>();
    }

    public int MachineId { get; set; }
    public string MachineName { get; set; }
    public string MachineManufacturer { get; set; }
    public string ModelNumber { get; set; }
    public string AssetNumber { get; set; }
    public string LocationNumber { get; set; }
    public virtual ICollection<MechanicMachine> JoinEntities { get; }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines.Include(machine => machine.JoinEntities).ThenInclude(join => join.Mechanic).FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int MechanicId)
    {
      if(MechanicId != 0)
      {
        _db.MechanicMachine.Add(new MechanicMachine() { MechanicId = MechanicId, MachineId = machine.MachineId});
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId});
    }

    public ActionResult AddMechanic(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.MechanicId = new SelectList(_db.Mechanics, "MechanicId", "MechanicName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddMechanic(Machine machine, int MechanicId)
    {
      if (MechanicId != 0)
      {
        _db.MechanicMachine.Add(new MechanicMachine() {MechanicId = MechanicId, MachineId = machine.MachineId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId});
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      List<MechanicMachine> thisMachineJoins = _db.MechanicMachine.ToList();
      foreach(MechanicMachine mm in thisMachineJoins)
      {
        if(mm.MachineId == id)
        {
          _db.MechanicMachine.Remove(mm);
        }
      }
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Remove(int id)
    {
      var thisJoin = _db.MechanicMachine.FirstOrDefault(mechanicmachine => mechanicmachine.MechanicMachineId == id);
      return View(thisJoin);
    }

    [HttpPost, ActionName("Remove")]
    public ActionResult RemoveConfirmed(int id)
    {
      var thisJoin = _db.MechanicMachine.FirstOrDefault(mechanicmachine => mechanicmachine.MechanicMachineId == id);
      _db.MechanicMachine.Remove(thisJoin);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = thisJoin.MachineId});
    }
  }
}

Factory/Controllers/MechanicsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MechanicsController : Controller
  {
    private readonly FactoryContext _db;

    public MechanicsController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Mechanic> model = _db.Mechanics.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.MechanicId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Mechanic mechanic)
    {
      _db.Mechanics.Add(mechanic);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMechanic = _db.Mechanics.Include(mechanic => mechanic.JoinEntities).ThenInclude(join => join.Machine).FirstOrDefault(mechanic => mechanic.MechanicId == id);
      return View(thisMechanic);
    }

    public ActionResult Edit(int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      return View(thisMechanic);
    }

    [HttpPost]
    public ActionResult Edit(Mechanic mechanic)
    {
      _db.Entry(mechanic).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = mechanic.MechanicId});
    }

    public ActionResult AddMachine (int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisMechanic);
    }

    [HttpPost]
    public ActionResult AddMachine(Mechanic mechanic, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.MechanicMachine.Add(new MechanicMachine() {MachineId = MachineId, MechanicId = mechanic.MechanicId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = mechanic.MechanicId});
    }

    public ActionResult Delete(int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      return View(thisMechanic);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      List<MechanicMachine> thisMechanicsJoins = _db.MechanicMachine.ToList();
      foreach(MechanicMachine mm in thisMechanicsJoins)
      {
        if(mm.MechanicId == id)
        {
          _db.MechanicMachine.Remove(mm);
        }
      }
      _db.Mechanics.Remove(thisMechanic);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Remove(int id)
    {
      var thisJoin = _db.MechanicMachine.FirstOrDefault(mechanicmachine => mechanicmachine.MechanicMachineId == id);
      return View(thisJoin);
    }

    [HttpPost, ActionName("Remove")]
    public ActionResult RemoveConfirmed(int id)
    {
      var thisJoin = _db.MechanicMachine.FirstOrDefault(mechanicmachine => mechanicmachine.MechanicMachineId == id);
      _db.MechanicMachine.Remove(thisJoin);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = thisJoin.MechanicId});
    }

  }
}

Factory/Views/Machines/AddMechanic.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a Mechanic</h2>

<h4>Add a Mechanic licensed to fix this machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select Mechanic: ")
  @Html.DropDownList("MechanicId")
  <br>
  <input type="submit" value="Save" class="btn btn-primary"/>
}

<p>@Html.ActionLink("Back to Machine", "Details", new { id = @Model.MachineId}, new { @class = "btn btn-primary"})</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine


<h4>Add a New Machine</h4>

@using (Html.BeginForm())
{
  <table>
    <tr>
      <td>@Html.Label("Machine Name: ")</td>
      <td>@Html.TextBoxFor(model => model.MachineName)</td>
    </tr>
    <tr>
      <td>@Html.Label("Machine Manufacturer: ")</td>
      <td>@Html.TextBoxFor(model => model.MachineManufacturer)</td>
    </tr>
    <tr>
      <td>@Html.Label("Model Number: ")</td>
      <td>@Html.TextBoxFor(model => model.ModelNumber)</td>
    </tr>
    <tr>
      <td>@Html.Label("Asset Number: ")</td>
      <td>@Html.TextBoxFor(model => model.AssetNumber)</td>
    </tr>
    <tr>
      <td>@Html.Label("Location Number: ")</td>
      <td>@Html.TextBoxFor(model => model.LocationNumber)</td>
    </tr>
  </table>
  <br>

    <input type="submit" value="Add new Machine" class="btn btn-primary" /> 
}
@Html.ActionLink("Cancel", "Index", null, null, new { @class = "btn btn-primary"})

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this machine?</h2>
<p>This will also delete all links from this Machine to their Mechanics</p>


@Html.Label("Machine Name: ") @Html.DisplayFor(model => model.MachineName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-primary"/>
}
@Html.ActionLink("Cancel", "Details", null, new {id = Model.MachineId}, new { @class = "btn btn-primary"})

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<table>
  <tr>
    <td>@Html.Label("Machine Name: ")</td>
    <td>@Html.DisplayFor(model => model.MachineName)</td>
  </tr>
  <tr>
    <td>@Html.Label("Machine Manufacturer: ")</td>
    <td>@Html.DisplayFor(model => model.MachineManufacturer)</td>
  </tr>
  <tr>
    <td>@Html.Label("Model Number: ")</td>
    <td>@Html.DisplayFor(model => model.ModelNumber)</td>
  </tr>
  <tr>
    <td>@Html.Label("Asset Number: ")</td>
    <td>@Html.DisplayFor(model => model.AssetNumber)</td>
  </tr>
  <tr>
    <td>@Html.Label("Location Number: ")</td>
    <td>@Html.DisplayFor(model => model.LocationNumber)</td>
  </tr>
</table>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Machine has no mechanics licensed to service.</p>
}
else
{
  <h4>Mechanics: </h4>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@Html.ActionLink($"{@join.Mechanic.MechanicName}", "Details", "Mechanics", new { id = join.Mechanic.MechanicId })</li> @Html.ActionLink("Remove", "Remove",  new { id = join.MechanicMachineId }, new {@class="btn btn-primary"})
    }
  </ul>
}

<p>@Html.ActionLink("Add a Mechanic", "AddMechanic", new { id = Model.MachineId }, new { @class = "btn btn-primary"})</p>

<p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId }, new { @class = "btn btn-primary"})</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId }, new { @class = "btn btn-primary"})</p>
<p>@Html.ActionLink("Back to list", "Index", null, null, new {@class = "btn btn-primary"})</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit this machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{

  @Html.HiddenFor(model => model.MachineId)
  <table>
    <tr>
      <td>@Html.Label("Machine Name: ")</td>
      <td>@Html.TextBoxFor(model => model.MachineName)</td>
    </tr>
    <tr>
      <td>@Html.Label("Machine Manufacturer: ")</td>
      <td>@Html.TextBoxFor(model => model.MachineManufacturer)</td>
    </tr>
    <tr>
      <td>@Html.Label("Model Number: ")</td>
      <td>@Html.TextBoxFor(model => model.ModelNumber)</td>
    </tr>
    <tr>
      <td>@Html.Label("Asset Number: ")</td>
      <td>@Html.TextBoxFor(model => model.AssetNumber)</td>
    </tr>
    <tr>
      <td>@Html.Label("Location Number: ")</td>
      <td>@Html.TextBoxFor(model => model.LocationNumber)</td>
    </tr>
  </table>
  <br>

  <input type="submit" value="Save" class="btn btn-primary" /> 
}
@Html.ActionLink("Cancel", "Details", null, new { id = Model.MachineId }, new { @class = "btn btn-primary"})

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>Machines</h1>

@if (@Model.Count == 0)
{
  <h3>No machines have been added yet!</h3>
} 

<ul>
  @foreach(Machine machine in Model)
  {
    <li>@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new Machine", "Create", null, null, new { @class = "btn btn-primary"})</p>

Factory/Views/Machines/Remove.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.MechanicMachine

<h2>Are you sure you want to Remove this Machine from this Mechanic?</h2>
<table>
  <tr>
    <td>@Html.Label("Mechanic Name: ")</td> 
    <td>@Html.DisplayFor(model => model.Mechanic.MechanicName)</td>
  </tr>
    <tr>
    <td>@Html.Label("Machine Name: ")</td> 
    <td>@Html.DisplayFor(model => model.Machine.MachineName)</td>
  </tr>
</table>

@using (Html.BeginForm())
{
  <input type="submit" value="Remove" class="btn btn-primary"/>
}

@Html.ActionLink("Cancel", "Details", null, new { id = Model.MachineId }, new { @class = "btn btn-primary"})