Factory/Models/Mechanic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Factory.Models
{
  public class Mechanic
  {
    public Mechanic()
    {
      this.JoinEntities = new HashSet<MechanicMachine>();
    }

    public int MechanicId { get; set; }
    public string MechanicName { get; set; }
    public string MechanicTitle { get; set; }

    public virtual ICollection<MechanicMachine> JoinEntities { get; }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines.Include(machine => machine.JoinEntities).ThenInclude(join => join.Mechanic).FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int MechanicId)
    {
      if(MechanicId != 0)
      {
        _db.MechanicMachine.Add(new MechanicMachine() { MechanicId = MechanicId, MachineId = machine.MachineId});
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId});
    }

    public ActionResult AddMechanic(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.MechanicId = new SelectList(_db.Mechanics, "MechanicId", "MechanicName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddMechanic(Machine machine, int MechanicId)
    {
      if (MechanicId != 0)
      {
        _db.MechanicMachine.Add(new MechanicMachine() {MechanicId = MechanicId, MachineId = machine.MachineId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId});
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      List<MechanicMachine> thisMachineJoins = _db.MechanicMachine.ToList();
      foreach(MechanicMachine mm in thisMachineJoins)
      {
        if(mm.MachineId == id)
        {
          _db.MechanicMachine.Remove(mm);
        }
      }
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Remove(int id)
    {
      var thisJoin = _db.MechanicMachine.FirstOrDefault(mechanicmachine => mechanicmachine.MechanicMachineId == id);
      return View(thisJoin);
    }

    [HttpPost, ActionName("Remove")]
    public ActionResult RemoveConfirmed(int id)
    {
      var thisJoin = _db.MechanicMachine.FirstOrDefault(mechanicmachine => mechanicmachine.MechanicMachineId == id);
      _db.MechanicMachine.Remove(thisJoin);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = thisJoin.MachineId});
    }
  }
}

Factory/Controllers/MechanicsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MechanicsController : Controller
  {
    private readonly FactoryContext _db;

    public MechanicsController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Mechanic> model = _db.Mechanics.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.MechanicId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Mechanic mechanic)
    {
      _db.Mechanics.Add(mechanic);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMechanic = _db.Mechanics.Include(mechanic => mechanic.JoinEntities).ThenInclude(join => join.Machine).FirstOrDefault(mechanic => mechanic.MechanicId == id);
      return View(thisMechanic);
    }

    public ActionResult Edit(int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      return View(thisMechanic);
    }

    [HttpPost]
    public ActionResult Edit(Mechanic mechanic)
    {
      _db.Entry(mechanic).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = mechanic.MechanicId});
    }

    public ActionResult AddMachine (int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisMechanic);
    }

    [HttpPost]
    public ActionResult AddMachine(Mechanic mechanic, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.MechanicMachine.Add(new MechanicMachine() {MachineId = MachineId, MechanicId = mechanic.MechanicId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = mechanic.MechanicId});
    }

    public ActionResult Delete(int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      return View(thisMechanic);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMechanic = _db.Mechanics.FirstOrDefault(mechanic => mechanic.MechanicId == id);
      List<MechanicMachine> thisMechanicsJoins = _db.MechanicMachine.ToList();
      foreach(MechanicMachine mm in thisMechanicsJoins)
      {
        if(mm.MechanicId == id)
        {
          _db.MechanicMachine.Remove(mm);
        }
      }
      _db.Mechanics.Remove(thisMechanic);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Remove(int id)
    {
      var thisJoin = _db.MechanicMachine.FirstOrDefault(mechanicmachine => mechanicmachine.MechanicMachineId == id);
      return View(thisJoin);
    }

    [HttpPost, ActionName("Remove")]
    public ActionResult RemoveConfirmed(int id)
    {
      var thisJoin = _db.MechanicMachine.FirstOrDefault(mechanicmachine => mechanicmachine.MechanicMachineId == id);
      _db.MechanicMachine.Remove(thisJoin);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = thisJoin.MechanicId});
    }

  }
}

Factory/Views/Mechanics/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Mechanic

<h2>Add a Machine</h2>

<h4>Add a Machine for this Mechanic: @Html.DisplayFor(model => model.MechanicName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MechanicId)

  @Html.Label("Select Machine")
  @Html.DropDownList( "MachineId" )

  <input type="submit" value="Save" />
}

@Html.ActionLink("Back to list", "Index", null, null, new { @class = "btn btn-primary"})

Factory/Views/Mechanics/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Mechanic

<h4>Add a New Mechanic</h4>

@using (Html.BeginForm())
{
    <table>
      <tr>
        <td>@Html.Label("Mechanic Name: ")</td> 
        <td>@Html.EditorFor(model => model.MechanicName)</td>
      </tr>
        <tr>
        <td>@Html.Label("Mechanic Title: ")</td> 
        <td>@Html.EditorFor(model => model.MechanicTitle)</td>
      </tr>
    </table>

    <input type="submit" value="Add new Mechanic" class="btn btn-primary" />
}
@Html.ActionLink("Cancel", "Index", null, null, new { @class = "btn btn-primary"})

Factory/Views/Mechanics/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Mechanic

<h2>Are you sure you want to delete this Mechanic?</h2>
<p>This will also delete all links from this Mechanic to their Machines</p>

@Html.Display("Mechanic Name"): @Html.DisplayFor(model => model.MechanicName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-primary"/>
}

@Html.ActionLink("Cancel", "Details", null, new { id = Model.MechanicId }, new { @class = "btn btn-primary"})

Factory/Views/Mechanics/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Mechanic

<h2>Mechanic Details</h2>
<hr />
<table>
  <tr>
    <td>@Html.Label("Mechanic Name: ")</td> 
    <td>@Html.DisplayFor(model => model.MechanicName)</td>
  </tr>
    <tr>
    <td>@Html.Label("Mechanic Title: ")</td> 
    <td>@Html.DisplayFor(model => model.MechanicTitle)</td>
  </tr>
</table>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Mechanic has no machines they are licensed to service.</p>
}
else
{
  <h5>Machines: </h5>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@Html.ActionLink($"{@join.Machine.MachineName}", "Details", "Machines", new { id = join.Machine.MachineId })</li> @Html.ActionLink("Remove", "Remove",  new { id = join.MechanicMachineId }, new {@class="btn btn-primary"})
    }
  </ul>
}

<p>@Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.MechanicId}, new { @class = "btn btn-primary"})</p>
<p>@Html.ActionLink("Edit Mechanic", "Edit", new { id = Model.MechanicId }, new { @class = "btn btn-primary"})</p>
<p>@Html.ActionLink("Delete Mechanic", "Delete", new { id = Model.MechanicId }, new { @class = "btn btn-primary"})</p>
<p>@Html.ActionLink("Back to list", "Index", null, null, new {@class = "btn btn-primary"})</p>

Factory/Views/Mechanics/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Mechanic

<h2>Edit</h2>

<h4>Edit this Mechanic: @Html.DisplayFor(model => model.MechanicName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MechanicId)

    <table>
      <tr>
        <td>@Html.Label("Mechanic Name: ")</td> 
        <td>@Html.EditorFor(model => model.MechanicName)</td>
      </tr>
        <tr>
        <td>@Html.Label("Mechanic Title: ")</td> 
        <td>@Html.EditorFor(model => model.MechanicTitle)</td>
      </tr>
    </table>
    <input type="submit" value="Save" class="btn btn-primary"/>
}

@Html.ActionLink("Cancel", "Details", null, new { id = Model.MechanicId }, new { @class = "btn btn-primary"})

Factory/Views/Mechanics/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Mechanic>;

<h1>Mechanic</h1>

@if (@Model.Count == 0)
{
  <h3>No mechanics have been added yet!</h3>
} 

@foreach (Mechanic mechanic in Model)
{
  <li>@Html.ActionLink($"{mechanic.MechanicName}", "Details", new { id = mechanic.MechanicId }) </li>
}

@Html.ActionLink("New Mechanic", "Create", null, null, new { @class = "btn btn-primary"})

Factory/Views/Mechanics/Remove.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.MechanicMachine

<h2>Are you sure you want to Remove this Machine from this Mechanic?</h2>


<table>
  <tr>
    <td>@Html.Label("Mechanic Name: ")</td> 
    <td>@Html.DisplayFor(model => model.Mechanic.MechanicName)</td>
  </tr>
    <tr>
    <td>@Html.Label("Machine Name: ")</td> 
    <td>@Html.DisplayFor(model => model.Machine.MachineName)</td>
  </tr>
</table>

@using (Html.BeginForm())
{
  <input type="submit" value="Remove" class="btn btn-primary"/>
}

@Html.ActionLink("Cancel", "Details", null, new { id = Model.MechanicId }, new { @class = "btn btn-primary"})